web/__init__.py
"""Medical cell detection."""

from __future__ import annotations

import json
import logging
import os
import typing

import flask
import flask_babel

__all__ = [
	"create_app",
	"get_config"
]
__version__ = "0.0.1"

logging.basicConfig(
	format="[%(asctime)s] %(levelname)s in %(module)s: %(message)s",
	level=getattr(
		logging,
		os.environ.get(
			"LOGGING_LEVEL",
			"DEBUG"
		)
	)
)


def get_config(
	skip_context_check: bool = False,
	config_location_envvar: str = "CONFIG_LOCATION",
	fallback_name: str = "config.json"
) -> typing.Dict[str, typing.Any]:
	"""Gets the current JSON config for this service.

	If this function is run in a Flask context and ``skip_context_check`` is
	:data:`True`, :attr:`flask.current_app.config` is returned. Otherwise, an
	attempt is made to use the ``config_location_envvar`` environment variable
	for the config file. If it exists, the location it points to will be used.
	Otherwise, the current working directory's ``fallback_name`` is used.

	:param config_location_envvar: The environment variable to use in order to
		find the custom config file. ``CONFIG_LOCATION`` by default.
	:param fallback_name: The filename to use when the environment variable is
		not set. Defaults to ``config.json``.

	.. warning::
		It's assumed that if the environment variable is set, the location is
		valid and the file exists. If it is not set, ``config.json`` must exist.

	:returns: The config, in a Python dictionary.
	"""

	if not skip_context_check and flask.has_app_context():
		return flask.current_app.config

	with open(
		os.environ.get(
			config_location_envvar,
			os.path.join(os.getcwd(), fallback_name)
		),
		"r",
		encoding="utf-8"
	) as config_file:
		return json.load(config_file)


def create_app() -> flask.Flask:
	r"""Creates a :class:`Flask <flask.Flask>` app with settings already applied.

	Loads the config from the file located where the ``CONFIG_LOCATION``
	environment variable describes, or ``$current_working_directory/config.json``
	if it's not set.

	Registers all blueprints in :mod:`.views`.

	:returns: The finished app.
	"""

	app = flask.Flask(__name__)

	with app.app_context():
		app.logger.info("Setting up app")

		app.logger.debug("Loading config file")

		app.config.update(get_config(skip_context_check=True))

		app.babel = flask_babel.Babel(app)

		from .views import detector_blueprint

		for blueprint in (detector_blueprint,):
			app.logger.debug("Registering blueprint: %s", blueprint)

			app.register_blueprint(blueprint)

	app.logger.info("App setup finished")

	return app

web/views/__init__.py
from .detector import detector_blueprint

__all__ = ["detector_blueprint"]
__version__ = "0.0.1"

web/views/detector.py
import base64
import binascii
import io

import flask
import magic
import requests
import werkzeug.exceptions

detector_blueprint = flask.Blueprint(
	"detector",
	__name__
)


@detector_blueprint.route("/", methods=["GET", "POST"])
def detect():
	if (
		flask.request.method == "POST" and
		"image" in flask.request.form and
		"visualize" in flask.request.form
	):
		visualize = (flask.request.form["visualize"] == "true")

		try:
			decoded_image = base64.b64decode(flask.request.form["image"], validate=True)
		except (ValueError, binascii.Error):
			raise werkzeug.exceptions.BadRequest

		image_buffer = io.BytesIO(decoded_image)

		image_type = magic.from_buffer(
			image_buffer.read(2048),
			mime=True
		)

		image_buffer.seek(0)

		if image_type not in (
			"image/png",
			"image/jpeg",
			"image/tiff",
			"image/bmp"
		):
			raise werkzeug.exceptions.BadRequest

		response = requests.post(
			f"{flask.current_app.config['SERVER_URL']}upload?image={0 if visualize else 1}",
			files={
				"file": (f"file.{image_type.split('/')[1]}", image_buffer)
			},
			timeout=120
		)

		if not response.ok:
			return flask.render_template(
				"detect_error.html",
				error=None
			), response.status_code

		if not visualize:
			return flask.render_template(
				"detect_result_noninteractive.html",
				image=base64.b64encode(response.raw)
			)
		else:
			response = response.json()
			
			return flask.render_template(
				"detect_result.html",
				image=flask.request.form["image"],
				cell_data=response["data"],
				width=response["shape"][1],
				height=response["shape"][0]
			)

	return flask.render_template("detect_start.html")

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{{ gettext('Medical cell detection') }}</title>
		
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='css/base.css') }}"
		>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='fonts/roboto/style.css') }}"
		>
	</head>
	<body>
		<header>
			<section class="header-main">
				<img
					src="{{ url_for('static', filename='images/logo.png') }}"
					alt="{{ gettext('Logo') }}"
					width="30"
					height="30"
				>
				<h1>{{ gettext('Medical cell detection') }}</h1>
			</section>
			<section class="header-other">
				POC
			</section>
		</header>
		{% block content %}{% endblock %}
	</body>
</html>

web/templates/detect_error.html
{% extends 'base.html' %}

{% block content %}
	<main>
		<section class="main-center text-center">
			<div class="error">
				{% if error is none %}
					{{ gettext("An unknown error has occurred. We apologize for the inconvenience.") }}
				{% endif %}
			</div>
		</section>
	</main>
{% endblock %}

web/templates/detect_result.html
{% extends 'base.html' %}

{% block content %}
	<script
		type="text/javascript"
		src="{{ url_for('static', filename='js/result.js') }}"
	></script>
	<script type="text/javascript">
		window.cellData = {{ cell_data|safe }};
		
		window.addEventListener(
			"DOMContentLoaded",
			function (event) {
				generateSvg(window.cellData);
			}
		);
	</script>
	
	<main>
		<section class="main-left text-center">
			<a href="{{ url_for('detector.detect') }}">
				<img
					src="{{ url_for('static', filename='images/arrow-left.svg') }}"
					alt="{{ gettext('Go back') }}"
					width="30"
				>
			</a><br><br>
			
			<input
				type="checkbox"
				name="show-core"
				id="show-core"
			>
			<label for="show-core">{{ gettext('Highlight cores') }}</label>
			<br>
			<input
				type="checkbox"
				name="show-shell"
				id="show-shell"
			>
			<label for="show-shell">{{ gettext('Highlight shells') }}</label>
		</section>
		<section class="main-center text-center">
			<div class="result-image-wrapper">
				<img
					id="result-image"
					src="data:image/png;base64,{{ image }}"
					alt="{{ gettext('Result image') }}"
				>
				<svg id="result-svg" class="result-svg" viewBox="0 0 {{ width }} {{ height }}"></svg>
			</div>
			
			<button id="download-json">{{ gettext('Export to JSON') }}</button>
			<button id="download-image">{{ gettext('Download image') }}</button>
			
			<br>
			
			<p>
				{{ gettext('There are a total of %s cells.').format(cell_data|length) }}
		</section>
	</main>
{% endblock %}

web/templates/detect_result_noninteractive.html
{% extends 'base.html' %}

{% block content %}
	<script
		type="text/javascript"
		src="{{ url_for('static', filename='js/result.js') }}"
	></script>
	
	<main>
		<section class="main-left text-center">
			<a href="{{ url_for('detector.detect') }}">
				<img
					src="{{ url_for('static', filename='images/arrow-left.svg') }}"
					alt="{{ gettext('Go back') }}"
					width="30"
				>
			</a>
		</section>
		<section class="main-center text-center">
			<img
				id="result-image"
				src="data:image/png;base64,{{ image }}"
				alt="{{ gettext('Result image') }}"
			>
		</section>
	</main>
{% endblock %}

web/templates/detect_start.html
{% extends 'base.html' %}

{% block content %}
	<script
		type="text/javascript"
		src="{{ url_for('static', filename='js/upload.js') }}"
	></script>
	<main>
		<section class="main-center text-center">
			<div>
				<div class="styled-file-input-wrapper">
					<button id="image-button" class="styled-file-input-button">{{ gettext('Upload image') }}</button>
					<input
						id="image"
						class="styled-file-input"
						type="file"
						id="image"
						name="image"
						accept="image/png, image/jpeg, image/bmp, image/tiff"
					>
				</div>
				<div id="visualize-wrapper">
					<input
						type="checkbox"
						id="visualize"
						name="visualize"
						checked
					>
					<label for="visualize">{{ gettext('Create an interactive map') }}</label>
				</div>
			</div>
			<small class="text-secondary" id="bottom-text">
				{{ gettext('PNG, JPEG, TIFF and BMP are supported.') }}
			</small>
		</section>
	</main>
{% endblock %}